// Comprehensive Plant Database with Hindi and English Information
export interface ComprehensivePlantData {
  english_name: string;
  hindi_name: string;
  sanskrit_name: string;
  scientific_name: string;
  family: string;
  description_english: string;
  description_hindi: string;
  uses_english: string;
  uses_hindi: string;
  preparation_english: string;
  preparation_hindi: string;
  parts_used_english: string;
  parts_used_hindi: string;
  properties_english: string;
  properties_hindi: string;
  precautions_english: string;
  precautions_hindi: string;
  dosage_english: string;
  dosage_hindi: string;
  therapeutic_actions_english: string;
  therapeutic_actions_hindi: string;
}

export const COMPREHENSIVE_PLANT_DATABASE: { [key: string]: ComprehensivePlantData } = {
  "tulsi": {
    english_name: "Tulsi",
    hindi_name: "तुलसी",
    sanskrit_name: "तुलसी",
    scientific_name: "Ocimum sanctum",
    family: "Lamiaceae",
    description_english: "Sacred herb with adaptogenic properties. Known for its respiratory benefits and stress relief qualities.",
    description_hindi: "अनुकूलनकारी गुणों वाली पवित्र जड़ी-बूटी। श्वसन संबंधी लाभ और तनाव से राहत के लिए प्रसिद्ध।",
    uses_english: "Respiratory health, immunity booster, stress relief, fever, cold, cough, asthma, bronchitis",
    uses_hindi: "श्वसन स्वास्थ्य, प्रतिरक्षा बूस्टर, तनाव से राहत, बुखार, सर्दी, खांसी, दमा, श्वसनी शोथ",
    preparation_english: "Fresh leaves can be chewed, made into tea, or taken as powder. Extract can be used topically.",
    preparation_hindi: "ताजे पत्ते चबाए जा सकते हैं, चाय बनाई जा सकती है, या पाउडर के रूप में लिया जा सकता है। अर्क बाहरी उपयोग के लिए।",
    parts_used_english: "Leaves, stems, seeds",
    parts_used_hindi: "पत्ती, तना, बीज",
    properties_english: "Warming, pungent, aromatic, adaptogenic, immunomodulator",
    properties_hindi: "उष्ण, तीक्ष्ण, सुगंधित, अनुकूलनकारी, प्रतिरक्षा संशोधक",
    precautions_english: "May lower blood sugar levels. Avoid during pregnancy. May interact with blood thinning medications.",
    precautions_hindi: "रक्त शर्करा का स्तर कम हो सकता है। गर्भावस्था में बचें। रक्त पतला करने वाली दवाओं के साथ प्रभाव डाल सकती है।",
    dosage_english: "5-10 fresh leaves daily, or 1-2 tsp dried powder with water",
    dosage_hindi: "प्रतिदिन 5-10 ताजे पत्ते, या 1-2 चम्मच सूखा पाउडर पानी के साथ",
    therapeutic_actions_english: "Adaptogenic, immunomodulator, expectorant, antioxidant, anti-inflammatory",
    therapeutic_actions_hindi: "अनुकूलनकारी, प्रतिरक्षा संशोधक, कफ निकालने वाला, एंटीऑक्सीडेंट, सूजन रोधी"
  },
  "turmeric": {
    english_name: "Turmeric",
    hindi_name: "हल्दी",
    sanskrit_name: "हरिद्रा",
    scientific_name: "Curcuma longa",
    family: "Zingiberaceae",
    description_english: "Golden spice with powerful anti-inflammatory and healing properties. Used extensively in cooking and medicine.",
    description_hindi: "सुनहरा मसाला जिसमें शक्तिशाली सूजन रोधी और उपचार गुण हैं। खाना पकाने और दवा में व्यापक रूप से उपयोग किया जाता है।",
    uses_english: "Anti-inflammatory, wound healing, digestive aid, arthritis, skin conditions, liver support",
    uses_hindi: "सूजन रोधी, घाव भरना, पाचन सहायक, गठिया, त्वचा की समस्याएं, यकृत समर्थन",
    preparation_english: "Fresh root can be grated, dried powder mixed with milk/water, paste for external application",
    preparation_hindi: "ताजी जड़ को कद्दूकस किया जा सकता है, सूखा पाउडर दूध/पानी के साथ मिलाकर, बाहरी उपयोग के लिए पेस्ट",
    parts_used_english: "Rhizome (underground stem), fresh or dried",
    parts_used_hindi: "प्रकंद (भूमिगत तना), ताजा या सूखा",
    properties_english: "Warming, bitter, pungent, anti-inflammatory, antioxidant",
    properties_hindi: "उष्ण, कड़वा, तीक्ष्ण, सूजन रोधी, एंटीऑक्सीडेंट",
    precautions_english: "May increase bleeding risk. Can interact with diabetes medications. Avoid large amounts if pregnant.",
    precautions_hindi: "रक्तस्राव का जोखिम बढ़ा सकता है। मधुमेह की दवाओं के साथ प्रभाव डाल सकता है। गर्भावस्था में अधिक मात्रा से बचें।",
    dosage_english: "1/2 to 1 tsp powder daily with meals, or fresh root 1-2 inches",
    dosage_hindi: "भोजन के साथ प्रतिदिन 1/2 से 1 चम्मच पाउडर, या 1-2 इंच ताजी जड़",
    therapeutic_actions_english: "Anti-inflammatory, hepatoprotective, antioxidant, antimicrobial",
    therapeutic_actions_hindi: "सूजन रोधी, यकृत सुरक्षात्मक, एंटीऑक्सीडेंट, रोगाणुरोधी"
  },
  "neem": {
    english_name: "Neem",
    hindi_name: "नीम",
    sanskrit_name: "निम्ब",
    scientific_name: "Azadirachta indica",
    family: "Meliaceae",
    description_english: "Sacred tree known as nature's pharmacy. Excellent for skin conditions and blood purification.",
    description_hindi: "प्रकृति की फार्मेसी के रूप में जाना जाने वाला पवित्र वृक्ष। त्वचा की समस्याओं और रक्त शुद्धीकरण के लिए उत्कृष्ट।",
    uses_english: "Antibacterial, antifungal, skin treatment, blood purification, diabetes support, dental health",
    uses_hindi: "जीवाणुरोधी, कवकरोधी, त्वचा उपचार, रक्त शुद्धीकरण, मधुमेह सहायक, दंत स्वास्थ्य",
    preparation_english: "Leaves can be chewed, made into paste, oil extracted, powder form available",
    preparation_hindi: "पत्तियों को चबाया जा सकता है, पेस्ट बनाया जा सकता है, तेल निकाला जा सकता है, पाउडर के रूप में उपलब्ध",
    parts_used_english: "Leaves, bark, oil, seeds",
    parts_used_hindi: "पत्तियां, छाल, तेल, बीज",
    properties_english: "Cooling, bitter, astringent, antimicrobial, blood purifying",
    properties_hindi: "शीतल, कड़वा, कसैला, रोगाणुरोधी, रक्त शुद्धीकरण",
    precautions_english: "Very bitter taste. May lower blood sugar. Avoid internal use during pregnancy.",
    precautions_hindi: "बहुत कड़वा स्वाद। रक्त शर्करा कम हो सकती है। गर्भावस्था में आंतरिक उपयोग से बचें।",
    dosage_english: "2-4 leaves daily (chewed), 1/2 tsp powder, topical application as needed",
    dosage_hindi: "प्रतिदिन 2-4 पत्ते (चबाकर), 1/2 चम्मच पाउडर, आवश्यकतानुसार बाहरी उपयोग",
    therapeutic_actions_english: "Antimicrobial, blood purifier, hepatoprotective, immunomodulator",
    therapeutic_actions_hindi: "रोगाणुरोधी, रक्त शोधक, यकृत सुरक्षात्मक, प्रतिरक्षा संशोधक"
  },
  "ginger": {
    english_name: "Ginger",
    hindi_name: "अदरक",
    sanskrit_name: "आर्द्रक",
    scientific_name: "Zingiber officinale",
    family: "Zingiberaceae",
    description_english: "Warming spice excellent for digestion and circulation. Natural remedy for nausea and inflammation.",
    description_hindi: "पाचन और परिसंचरण के लिए उत्कृष्ट उष्ण मसाला। मतली और सूजन के लिए प्राकृतिक उपचार।",
    uses_english: "Digestive aid, anti-nausea, circulation, cold and flu, motion sickness, inflammation",
    uses_hindi: "पाचन सहायक, मतली रोधी, परिसंचरण, सर्दी और फ्लू, यात्रा बीमारी, सूजन",
    preparation_english: "Fresh root can be grated into tea, chewed raw, dried powder used in cooking",
    preparation_hindi: "ताजी जड़ को चाय में कद्दूकस किया जा सकता है, कच्चा चबाया जा सकता है, सूखा पाउडर खाना पकाने में उपयोग",
    parts_used_english: "Fresh or dried rhizome",
    parts_used_hindi: "ताजा या सूखा प्रकंद",
    properties_english: "Warming, pungent, stimulating, carminative, anti-inflammatory",
    properties_hindi: "उष्ण, तीक्ष्ण, उत्तेजक, वायुनाशक, सूजन रोधी",
    precautions_english: "May increase bleeding risk. Can cause heartburn in sensitive individuals. Use cautiously with gallstones.",
    precautions_hindi: "रक्तस्राव का जोखिम बढ़ा सकता है। संवेदनशील व्यक्तियों में सीने में जलन हो सकती है। पित्त की पथरी के साथ सावधानी से उपयोग करें।",
    dosage_english: "1-2 inches fresh root daily, or 1/2 tsp dried powder",
    dosage_hindi: "प्रतिदिन 1-2 इंच ताजी जड़, या 1/2 चम्मच सूखा पाउडर",
    therapeutic_actions_english: "Digestive stimulant, anti-inflammatory, circulatory stimulant, anti-emetic",
    therapeutic_actions_hindi: "पाचन उत्तेजक, सूजन रोधी, परिसंचरण उत्तेजक, मतली रोधी"
  },
  "aloe_vera": {
    english_name: "Aloe Vera",
    hindi_name: "एलोवेरा",
    sanskrit_name: "कुमारी",
    scientific_name: "Aloe barbadensis",
    family: "Asphodelaceae",
    description_english: "Succulent plant with cooling gel excellent for skin healing and internal digestive support.",
    description_hindi: "शीतल जेल वाला रसीला पौधा जो त्वचा की चिकित्सा और आंतरिक पाचन सहायता के लिए उत्कृष्ट है।",
    uses_english: "Skin healing, burns, wounds, digestive support, constipation, skin moisturizing",
    uses_hindi: "त्वचा चिकित्सा, जलन, घाव, पाचन सहायक, कब्ज, त्वचा नमीकरण",
    preparation_english: "Fresh gel from leaves applied topically, small amounts can be consumed internally",
    preparation_hindi: "पत्तियों से ताजा जेल बाहरी रूप से लगाया जाता है, छोटी मात्रा में आंतरिक सेवन किया जा सकता है",
    parts_used_english: "Leaf gel (mucilage)",
    parts_used_hindi: "पत्ती जेल (श्लेष्म)",
    properties_english: "Cooling, moisturizing, healing, anti-inflammatory, laxative",
    properties_hindi: "शीतल, नमी प्रदान करने वाला, उपचारक, सूजन रोधी, रेचक",
    precautions_english: "May cause diarrhea if taken internally in large amounts. Avoid during pregnancy and breastfeeding.",
    precautions_hindi: "बड़ी मात्रा में आंतरिक सेवन से दस्त हो सकते हैं। गर्भावस्था और स्तनपान के दौरान बचें।",
    dosage_english: "Topical: Apply fresh gel as needed. Internal: 1-2 tbsp gel (cautiously)",
    dosage_hindi: "बाहरी: आवश्यकतानुसार ताजा जेल लगाएं। आंतरिक: 1-2 चम्मच जेल (सावधानी से)",
    therapeutic_actions_english: "Wound healing, anti-inflammatory, moisturizing, mild laxative",
    therapeutic_actions_hindi: "घाव भरना, सूजन रोधी, नमी प्रदान करना, हल्का रेचक"
  },
  "ashwagandha": {
    english_name: "Ashwagandha",
    hindi_name: "अश्वगंधा",
    sanskrit_name: "अश्वगंधा",
    scientific_name: "Withania somnifera",
    family: "Solanaceae",
    description_english: "Powerful adaptogen known as Indian winter cherry. Excellent for stress management and energy.",
    description_hindi: "भारतीय शीत चेरी के रूप में जाना जाने वाला शक्तिशाली अनुकूलनकारी। तनाव प्रबंधन और ऊर्जा के लिए उत्कृष्ट।",
    uses_english: "Stress relief, energy boost, sleep support, immunity, muscle strength, cognitive function",
    uses_hindi: "तनाव राहत, ऊर्जा वृद्धि, नींद सहायक, प्रतिरक्षा, मांसपेशी शक्ति, संज्ञानात्मक कार्य",
    preparation_english: "Root powder mixed with warm milk or water, capsules, tinctures available",
    preparation_hindi: "जड़ का पाउडर गर्म दूध या पानी के साथ मिलाकर, कैप्सूल, टिंचर उपलब्ध",
    parts_used_english: "Root (primarily), leaves occasionally",
    parts_used_hindi: "जड़ (मुख्यतः), कभी-कभी पत्तियां",
    properties_english: "Warming, bitter, adaptogenic, nervine, rejuvenative",
    properties_hindi: "उष्ण, कड़वा, अनुकूलनकारी, नर्वाइन, कायाकल्प",
    precautions_english: "May increase sedation with medications. Avoid with autoimmune conditions. May affect thyroid function.",
    precautions_hindi: "दवाओं के साथ बेहोशी बढ़ सकती है। स्वप्रतिरक्षी स्थितियों से बचें। थायरॉयड कार्य को प्रभावित कर सकता है।",
    dosage_english: "1-2 tsp root powder daily with warm milk, preferably evening",
    dosage_hindi: "गर्म दूध के साथ प्रतिदिन 1-2 चम्मच जड़ का पाउडर, अधिमानतः शाम को",
    therapeutic_actions_english: "Adaptogenic, anxiolytic, immunomodulator, rejuvenative",
    therapeutic_actions_hindi: "अनुकूलनकारी, चिंता रोधی, प्रतिरक्षा संशोधक, कायाकल्प"
  },
  "amla": {
    english_name: "Amla",
    hindi_name: "आंवला",
    sanskrit_name: "आमलकी",
    scientific_name: "Emblica officinalis",
    family: "Phyllanthaceae",
    description_english: "Vitamin C powerhouse fruit, considered one of the most important Ayurvedic herbs for longevity.",
    description_hindi: "विटामिन सी से भरपूर फल, दीर्घायु के लिए सबसे महत्वपूर्ण आयुर्वेदिक जड़ी-बूटियों में से एक माना जाता है।",
    uses_english: "High vitamin C, immunity, hair care, skin health, antioxidant, eye health, liver support",
    uses_hindi: "उच्च विटामिन सी, प्रतिरक्षा, बाल की देखभाल, त्वचा स्वास्थ्य, एंटीऑक्सीडेंट, आंखों का स्वास्थ्य, यकृत सहायता",
    preparation_english: "Fresh fruit juice, dried powder, pickles, candied form, oil for hair",
    preparation_hindi: "ताजे फल का रस, सूखा पाउडर, अचार, मिठाई रूप, बालों के लिए तेल",
    parts_used_english: "Fresh fruit, dried powder",
    parts_used_hindi: "ताजा फल, सूखा पाउडर",
    properties_english: "Cooling, sour, astringent, antioxidant, rejuvenative",
    properties_hindi: "शीतल, खट्टा, कसैला, एंटीऑक्सीडेंट, कायाकल्प",
    precautions_english: "Very high vitamin C may cause acidity in sensitive individuals. Fresh fruit is quite sour.",
    precautions_hindi: "अत्यधिक विटामिन सी संवेदनशील व्यक्तियों में अम्लता का कारण हो सकता है। ताजा फल काफी खट्टा होता है।",
    dosage_english: "1-2 fresh fruits daily, or 1 tsp powder with water in morning",
    dosage_hindi: "प्रतिदिन 1-2 ताजे फल, या सुबह पानी के साथ 1 चम्मच पाउडर",
    therapeutic_actions_english: "Antioxidant, immunomodulator, hepatoprotective, anti-aging",
    therapeutic_actions_hindi: "एंटीऑक्सीडेंट, प्रतिरक्षा संशोधक, यकृत सुरक्षात्मक, वृद्धावस्था रोधी"
  },
  "mint": {
    english_name: "Mint",
    hindi_name: "पुदीना",
    sanskrit_name: "पुदीना",
    scientific_name: "Mentha spicata",
    family: "Lamiaceae",
    description_english: "Cooling herb excellent for digestion and respiratory issues. Refreshing taste and aroma.",
    description_hindi: "पाचन और श्वसन संबंधी समस्याओं के लिए उत्कृष्ट शीतल जड़ी-बूटी। ताज़गी भरा स्वाद और सुगंध।",
    uses_english: "Digestive aid, cooling, respiratory support, nausea, bad breath, headache relief",
    uses_hindi: "पाचन सहायक, शीतलता, श्वसन सहायक, मतली, सांस की बदबू, सिरदर्द राहत",
    preparation_english: "Fresh leaves in tea, chewed raw, essential oil, dried herb",
    preparation_hindi: "चाय में ताजे पत्ते, कच्चा चबाकर, आवश्यक तेल, सूखी जड़ी-बूटी",
    parts_used_english: "Fresh leaves primarily",
    parts_used_hindi: "मुख्यतः ताजे पत्ते",
    properties_english: "Cooling, pungent, aromatic, carminative, antispasmodic",
    properties_hindi: "शीतल, तीक्ष्ण, सुगंधित, वायुनाशक, ऐंठन रोधी",
    precautions_english: "Generally safe. May cause heartburn in some individuals. Essential oil should be diluted.",
    precautions_hindi: "आम तौर पर सुरक्षित। कुछ व्यक्तियों में सीने में जलन हो सकती है। आवश्यक तेल को पतला करना चाहिए।",
    dosage_english: "5-10 fresh leaves daily, or 1 cup mint tea",
    dosage_hindi: "प्रतिदिन 5-10 ताजे पत्ते, या 1 कप पुदीना चाय",
    therapeutic_actions_english: "Digestive stimulant, cooling, antispasmodic, carminative",
    therapeutic_actions_hindi: "पाचन उत्तेजक, शीतल, ऐंठन रोधी, वायुनाशक"
  },
  "fenugreek": {
    english_name: "Fenugreek",
    hindi_name: "मेथी",
    sanskrit_name: "मेथिका",
    scientific_name: "Trigonella foenum-graecum",
    family: "Fabaceae",
    description_english: "Seeds and leaves both valuable for blood sugar control and lactation support.",
    description_hindi: "रक्त शर्करा नियंत्रण और स्तनपान सहायता के लिए बीज और पत्तियां दोनों मूल्यवान हैं।",
    uses_english: "Blood sugar control, lactation support, digestive health, cholesterol management",
    uses_hindi: "रक्त शर्करा नियंत्रण, स्तनपान सहायक, पाचन स्वास्थ्य, कोलेस्ट्रॉल प्रबंधन",
    preparation_english: "Seeds soaked overnight and consumed, fresh leaves as vegetable, powder form",
    preparation_hindi: "बीज रात भर भिगोकर सेवन, ताजी पत्तियां सब्जी के रूप में, पाउडर रूप",
    parts_used_english: "Seeds, fresh leaves",
    parts_used_hindi: "बीज, ताजी पत्तियां",
    properties_english: "Warming, bitter, mucilaginous, hypoglycemic",
    properties_hindi: "उष्ण, कड़वा, श्लेष्मी, हाइपोग्लाइसेमिक",
    precautions_english: "May lower blood sugar significantly. Can interact with diabetes medications. May cause body odor.",
    precautions_hindi: "रक्त शर्करा में महत्वपूर्ण कमी हो सकती है। मधुमेह की दवाओं के साथ प्रभाव डाल सकता है। शरीर की गंध का कारण हो सकता है।",
    dosage_english: "1-2 tsp soaked seeds in morning, or fresh leaves as vegetable",
    dosage_hindi: "सुबह 1-2 चम्मच भीगे हुए बीज, या ताजी पत्तियां सब्जी के रूप में",
    therapeutic_actions_english: "Hypoglycemic, galactagogue, digestive, anti-inflammatory",
    therapeutic_actions_hindi: "हाइपोग्लाइसेमिक, दूध बढ़ाने वाला, पाचक, सूजन रोधी"
  },
  "cinnamon": {
    english_name: "Cinnamon",
    hindi_name: "दालचीनी",
    sanskrit_name: "त्वक्",
    scientific_name: "Cinnamomum verum",
    family: "Lauraceae",
    description_english: "Aromatic bark spice with blood sugar regulating and antimicrobial properties.",
    description_hindi: "रक्त शर्करा नियंत्रण और रोगाणुरोधी गुणों के साथ सुगंधित छाल मसाला।",
    uses_english: "Blood sugar regulation, antimicrobial, digestive warming, circulation",
    uses_hindi: "रक्त शर्करा नियंत्रण, रोगाणुरोधी, पाचन उष्णता, परिसंचरण",
    preparation_english: "Inner bark powder used in cooking, tea, capsules available",
    preparation_hindi: "आंतरिक छाल का पाउडर खाना पकाने में उपयोग, चाय, कैप्सूल उपलब्ध",
    parts_used_english: "Inner bark",
    parts_used_hindi: "आंतरिक छाल",
    properties_english: "Warming, sweet, pungent, antimicrobial, hypoglycemic",
    properties_hindi: "उष्ण, मीठा, तीक्ष्ण, रोगाणुरोधी, हाइपोग्लाइसेमिक",
    precautions_english: "May interact with blood thinners. Large amounts may be liver toxic (cassia variety). Monitor blood sugar.",
    precautions_hindi: "रक्त पतला करने वाली दवाओं के साथ प्रभाव डाल सकता है। बड़ी मात्रा में यकृत विषाक्त हो सकता है (कैसिया किस्म)। रक्त शर्करा की निगरानी करें।",
    dosage_english: "1/2 to 1 tsp powder daily with meals",
    dosage_hindi: "भोजन के साथ प्रतिदिन 1/2 से 1 चम्मच पाउडर",
    therapeutic_actions_english: "Hypoglycemic, antimicrobial, circulatory stimulant, digestive",
    therapeutic_actions_hindi: "हाइपोग्लाइसेमिक, रोगाणुरोधी, परिसंचरण उत्तेजक, पाचक"
  }
};